#!/usr/bin/env ruby

require_relative 'find_chars'

while file = ARGV.pop do
  data = FindChars.new(file)
  puts file.dup.red
  puts data.find_non_ascii
end

# test = FindChars.new 'test.txt'
# p test.find_non_ascii